### ISSUE TITLE
git2 ssh credentials issues

### ISSUE THREAD

**Issue by jedahan** [jedahan/zr#42]
split from #41 

> The compiled version works fine except it unable to fetch repositories.jedahan/zr selected as an example repo

```
$ RUST_BACKTRACE=full ./zr jedahan/zr
cloning https://github.com/jedahan/zr into "/Users/eirnym/Library/Caches/zr/jedahan/zr"
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { code: -16, klass: 23, message: "authentication required but no callback set" }', src/plugin.rs:22:60
stack backtrace:
   0:        0x100b7d344 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hb005c7b0db18e81c
   1:        0x100b8a3c4 - core::fmt::write::hd5dc98bbb37df0ea
   2:        0x100b5d180 - std::io::Write::write_fmt::h042e9f2909d3f218
   3:        0x100b7d198 - std::sys_common::backtrace::print::h6f40cdd50ebad80c
   4:        0x100b5d9b4 - std::panicking::default_hook::{{closure}}::hf87eed59167f92bd
   5:        0x100b5d7a0 - std::panicking::default_hook::h8fd4653aa15f3663
   6:        0x100b5def0 - std::panicking::rust_panic_with_hook::h35d52c7b2c1a812e
   7:        0x100b7d5fc - std::panicking::begin_panic_handler::{{closure}}::h0b6f57be552c83ee
   8:        0x100b7d414 - std::sys_common::backtrace::__rust_end_short_backtrace::hccd979d3efaf26cb
   9:        0x100b5db50 - _rust_begin_unwind
  10:        0x100b978b0 - core::panicking::panic_fmt::h8c741ce671c330d0
  11:        0x100b97680 - core::result::unwrap_failed::h4840784c52597da0
  12:        0x10096a558 - core::result::Result<T,E>::unwrap::hefb636d91bdc29a0
                               at /opt/local/libexec/rust/src/rustc-1.71.1-src/library/core/src/result.rs:1076:23
  13:        0x100952dc0 - zr::plugin::Plugin::clone_if_empty::he830949ac662143c
                               at /Users/eirnym/Developer/random/zsh_plugin_manager_speed/zr/src/plugin.rs:22:13
  14:        0x100952f14 - zr::plugin::Plugin::new::h431893b1b5604a19
                               at /Users/eirnym/Developer/random/zsh_plugin_manager_speed/zr/src/plugin.rs:42:9
  15:        0x10095b288 - zr::plugins::Plugins::new::h94d5b0f5ad392633
                               at /Users/eirnym/Developer/random/zsh_plugin_manager_speed/zr/src/plugins.rs:68:33
  16:        0x100963894 - zr::load::h2352131748569891
                               at /Users/eirnym/Developer/random/zsh_plugin_manager_speed/zr/src/main.rs:59:12
  17:        0x10096315c - zr::main::hd3cec197118ac393
                               at /Users/eirnym/Developer/random/zsh_plugin_manager_speed/zr/src/main.rs:31:27
  18:        0x10095bd48 - core::ops::function::FnOnce::call_once::ha77fa836e0a309b8
                               at /opt/local/libexec/rust/src/rustc-1.71.1-src/library/core/src/ops/function.rs:250:5
  19:        0x10096207c - std::sys_common::backtrace::__rust_begin_short_backtrace::h56e8e90aef06863f
                               at /opt/local/libexec/rust/src/rustc-1.71.1-src/library/std/src/sys_common/backtrace.rs:135:18
  20:        0x100959afc - std::rt::lang_start::{{closure}}::h59b60254073d6017
                               at /opt/local/libexec/rust/src/rustc-1.71.1-src/library/std/src/rt.rs:166:18
  21:        0x100b5da40 - std::panicking::try::hd60736db1a330482
  22:        0x100b79d98 - std::rt::lang_start_internal::he3aa91ba7dc1ac47
  23:        0x100959ac8 - std::rt::lang_start::hc2e5e0ff45c64b8a
                               at /opt/local/libexec/rust/src/rustc-1.71.1-src/library/std/src/rt.rs:165:17
  24:        0x100963b90 - _main
```
> My git config contains following lines and works perfectly with other commands.

```
[url "ssh://git@github.com/"]
    insteadOf = https://github.com/
```

**Comment by jedahan** [comment]
@eirnym If you comment out the custom config (ssh instead of https) does that work? If so, we can clarify the issue - I do not think I implemented an ssh credentials helper, and would love help in doing so.

**Comment by jedahan** [comment]
https://docs.rs/git2/latest/git2/build/struct.RepoBuilder.html which might add an annoying amount of interaction. I wonder if theres a decent 'default' credentials helper...

**Comment by jedahan** [comment]
https://github.com/davidB/git2_credentials

**Comment by eirnym** [comment]
I will be happy if the plugin manager will just run `git clone` or `git checkout`. For me personally dependency on an external command especially I have a custom configuration is understandable.

**Comment by eirnym** [comment]
And I have a private keys with default name as a bate. So please, be careful when parsing ssh configs.

**Comment by jedahan** [comment]
Originally this project was just a shell script, which is way better for running external commands than rust - I can see if I can find that version of it somewhere, as its probably more robust than zr is.

**Comment by eirnym** [comment]
I plan to make a few git utils from shell to git, so I'll try to make this auth part and I'll share my findings with you when my findings would be successful

**Comment by jedahan** [comment]
realistically I will not get around to implementing credentials support, but happy to review, test, and merge anyone who wants to contribute one
